source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd

applications:
  - name: app-of-apps
    project: gitops
    enabled: true
    sourcePath: charts/app-of-apps
    serverName: in-cluster
    helmValues:
      - ../../global-configuration.yaml

  - name: common
    project: common
    enabled: true
    sourcePath: charts/app-of-apps
    serverName: in-cluster
    helmValues:
      - ../../environments/common/configuration.yaml

  - name: dev
    project: dev
    enabled: true
    sourcePath: charts/app-of-apps
    serverName: in-cluster
    helmValues:
      - ../../environments/dev/configuration.yaml

  #- name: demo
  #  project: demo
  #  enabled: true
  #  sourcePath: charts/app-of-apps
  #  helmValues:
  #    - ../../environments/demo/configuration.yaml

projects:
  - name: gitops
    enabled: true
    destinations:
      - namespace: "*"
        server: "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
  - name: common
    enabled: true
    destinations:
      - namespace: "*"
        name: "in-cluster"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
  - name: dev
    enabled: true
    destinations:
      - namespace: "*"
        name: "dev-cluster"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
  #- name: demo
  #  enabled: true
  #  destinations:
  #    - namespace: "*"
  #      name: "*"
  #  clusterResourceWhitelist:
  #    - group: "*"
  #      kind: "*"
