apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    targetPort: {{ .Values.service.port }}
    port: {{ .Values.server.http.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
