apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-spring-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}-spring-config
data:
   application.json: | 
            {{- toPrettyJson .Values.properties | nindent 5}}
