apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "merlot-edc.fullname" . }}
  labels:
    {{- include "merlot-edc.labels" . | nindent 4 }}
data:
  edc.properties: |
    {{ .Values.edc.properties | indent 4 | trim }}