apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "merlot-edc.fullname" . }}
  labels:
    {{- include "merlot-edc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "merlot-edc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: edc
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "merlot-edc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "merlot-edc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}      
      initContainers:
        - name: init-decode-secret
          image: busybox
          command:
            - "sh"
            - "-c"
            - |
              echo "Starting..."
              file_path=$(find /mnt/secrets -name "keystore.pfx" -print -quit);              
              if [ -n "$file_path" ]; then
                echo "Found certificate"
                base64 -d "$file_path" > "/mnt/decoded/keystore.pfx" 2>/dev/null || cp "$file_path" "/mnt/decoded/keystore.pfx";
              fi
              echo "Done...";
          volumeMounts:
          {{- with .Values.secretVolumes }}
            {{- range . }}
            - name: {{ .secretName }}
              mountPath: /mnt/secrets/{{ .secretName }}
            {{- end }}            
          {{- end }}
            - name: decoded-secret
              mountPath: /mnt/decoded
      containers:
        - name: reverse-proxy
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag | default "latest" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
        - name: edc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.edc.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }} 
          {{- end }}
          {{- if .Values.envFromSecret }}
          envFrom:
            {{- range $secret := .Values.envFromSecret }}
            - secretRef:
                name: "{{ $secret }}"
            {{- end }} 
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.secretVolumes }}
            {{- range . }}
            - name: {{ .secretName }}
              mountPath: /mnt/secrets/{{ .secretName }}
            {{- end }}            
          {{- end }}
            - name: decoded-secret
              mountPath: /mnt/decoded
            - name: properties
              mountPath: /opt/config
      volumes:
      {{- with .Values.secretVolumes }}
        {{- range . }}
        - name: {{ .secretName }}
          secret:
            secretName: {{ .secretName }}
        {{- end }}        
      {{- end }}
        - name: decoded-secret
          emptyDir: {}
        - name: properties
          configMap:
            name: {{ include "merlot-edc.fullname" . }}
            items:
            - key: edc.properties
              path: edc.properties
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
