apiVersion: v1
kind: Secret
metadata:
  name: {{ include "merlot-edc.fullname" . }}-config
  labels:
    {{- include "merlot-edc.labels" . | nindent 4 }}
type: Opaque
stringData:
  EDC_API_AUTH_KEY: {{ .Values.secrets.EDC_API_AUTH_KEY }}
  EDC_KEYSTORE_PASSWORD: {{ .Values.secrets.EDC_KEYSTORE_PASSWORD }}
  EDC_IONOS_ACCESS_KEY: {{ .Values.secrets.EDC_IONOS_ACCESS_KEY }}
  EDC_IONOS_SECRET_KEY: {{ .Values.secrets.EDC_IONOS_SECRET_KEY }}
  EDC_IONOS_TOKEN: {{ .Values.secrets.EDC_IONOS_TOKEN }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "merlot-edc.fullname" . }}-keystore
  labels:
    {{- include "merlot-edc.labels" . | nindent 4 }}
data:
  keystore.pfx: {{ .Values.edc.keystore | quote }}
