{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "merlot-edc.serviceAccountName" . }}
  labels:
    {{- include "merlot-edc.labels" . | nindent 4 }}
{{- end }}
