apiVersion: v1
kind: Service
metadata:
  name: {{ include "gxfs-catalog.fullname" . }}-neo4j
  labels:
    {{- include "gxfs-catalog.neo4jLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      protocol: TCP
  selector:
    {{- include "gxfs-catalog.neo4jSelectorLabels" . | nindent 4 }}
