source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: demo

applications:
  - name: demo-marketplace
    namespace: demo
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/demo/marketplace.yaml"

  - name: demo-keycloak
    namespace: demo
    enabled: true
    sources:
      - ref: keycloak
      - repoURL: https://codecentric.github.io/helm-charts
        sourceRef: 18.4.0
        chartName: keycloak
        helmValues:
          - "$keycloak/environments/demo/keycloak.yaml"

  - name: demo-gxfs-catalog
    namespace: demo
    enabled: true
    sourcePath: charts/gxfs-catalog
    helmValues:
      - "../../environments/demo/gxfs-catalog.yaml"

  - name: demo-shared-resources
    namespace: demo
    enabled: true
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/demo/shared-resources.yaml"

  - name: demo-aaam-orchestrator
    namespace: demo
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/aaam-orchestrator.yaml"

  - name: demo-creation-wizard-api
    namespace: demo
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/creation-wizard-api.yaml"

  - name: demo-organisations-orchestrator
    namespace: demo
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/organisations-orchestrator.yaml"

  - name: demo-serviceoffering-orchestrator
    namespace: demo
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/serviceoffering-orchestrator.yaml"
