source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: demo

applications:
  - name: demo-marketplace
    namespace: demo
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/demo/marketplace.yaml"

  - name: demo-aaam-orchestrator
    namespace: demo
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/aaam-orchestrator.yaml"
