source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: demo

applications:
  - name: marketplace
    namespace: merlot
    enabled: true
    sourcePath: charts/marketplace
    serverName: demo-cluster
    helmValues:
      - "../../environments/demo/marketplace.yaml"

  - name: keycloak
    namespace: keycloak
    enabled: true
    serverName: demo-cluster
    sources:
      - ref: keycloak
      - repoURL: https://codecentric.github.io/helm-charts
        sourceRef: ~18.4.3
        chartName: keycloak
        helmValues:
          - "$keycloak/environments/demo/keycloak.yaml"

  - name: rabbitmq
    namespace: rabbitmq
    enabled: true
    serverName: demo-cluster
    sources:
      - ref: rabbitmq
      - repoURL: https://charts.bitnami.com/bitnami
        sourceRef: 11.16.2
        chartName: rabbitmq
        helmValues:
          - "$rabbitmq/environments/demo/rabbitmq.yaml"

  - name: gxfs-catalog
    namespace: gxfs
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/gxfs-catalog
    helmValues:
      - "../../environments/demo/gxfs-catalog.yaml"

  - name: shared-resources
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/demo/shared-resources.yaml"

  - name: aaam-orchestrator
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/aaam-orchestrator.yaml"

  - name: organisations-orchestrator
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/organisations-orchestrator.yaml"

  - name: creation-wizard-api
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/creation-wizard-api.yaml"

  - name: serviceoffering-orchestrator
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/serviceoffering-orchestrator.yaml"

  - name: contract-orchestrator
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/contract-orchestrator.yaml"

  - name: pdfservice
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/demo/pdfservice.yaml"

  - name: edc-1
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/demo/edc-1.yaml"

  - name: edc-2
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/demo/edc-2.yaml"

  - name: edc-imc
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-imc.yaml"

  - name: edc-chempoint
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-chempoint.yaml"

  - name: edc-headai
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-headai.yaml"

  - name: edc-lightcast
    namespace: merlot
    enabled: true
    serverName: demo-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-lightcast.yaml"
