replicaCount: 1

image:
  repository: ghcr.io/merlot-education/merlot-edc
  pullPolicy: IfNotPresent
  tag: e6190ae

service:
  type: LoadBalancer
  port: 80

env:
  EDC_PARTICIPANT_ID: # DAPS Client ID
  WEB_HTTP_PORT: 9191
  WEB_HTTP_PATH: /api
  WEB_HTTP_MANAGEMENT_PORT: 9192
  WEB_HTTP_MANAGEMENT_PATH: /management
  WEB_HTTP_PROTOCOL_PORT: 9193
  WEB_HTTP_PROTOCOL_PATH: /protocol
  WEB_HTTP_PUBLIC_PORT: 9194
  WEB_HTTP_PUBLIC_PATH: /public
  WEB_HTTP_CONTROL_PORT: 9195
  WEB_HTTP_CONTROL_PATH: /control
  EDC_DSP_CALLBACK_ADDRESS: http://localhost:9193/protocol
  EDC_VAULT: /opt/vault/vault.properties
  EDC_KEYSTORE: /opt/config/keystore.pfx
  EDC_OAUTH_CLIENT_ID: # DAPS Client ID
  EDC_OAUTH_PROVIDER_JWKS_URL: # DAPS JWKS URL
  EDC_OAUTH_TOKEN_URL: # DAPS Token URL
  EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
  EDC_OAUTH_CERTIFICATE_ALIAS: 1
  EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
  EDC_IAM_TOKEN_SCOPE: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  EDC_IONOS_ENDPOINT: # IONOS S3 Endpoint
envFromSecret:
  - merlot-edc-config

secrets:
  EDC_API_AUTH_KEY: # Connector API Auth Key
  EDC_KEYSTORE_PASSWORD: # Keystore Password
  EDC_IONOS_ACCESS_KEY: # IONOS S3 Access Key
  EDC_IONOS_SECRET_KEY: # IONOS S3 Secret Key
  EDC_IONOS_TOKEN: # IONOS API Token

edc:
  ports:
    - name: api
      port: 9191
    - name: management
      port: 9192
    - name: protocol
      port: 9193
    - name: public
      port: 9194
    - name: control
      port: 9195
  keystore: # Keystore encoded as Base64

nginx:
  image: nginx
  tag: 1.25.1

serviceAccount:
  create: true
  name: merlot-edc
