source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: common

applications:
  - name: pgadmin
    namespace: common
    enabled: true
    serverName: in-cluster
    sources:
      - ref: pgadmin
      - repoURL: https://helm.runix.net
        sourceRef: ~1.23.0
        chartName: pgadmin4
        helmValues:
          - "$pgadmin/environments/common/pgadmin.yaml"
  - name: ocm-command-center
    namespace: common
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/common/ocm-command-center.yaml"
        sourcePath: charts/ocm-command-center
        name: ocm-command-center
