apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 5050
        runAsGroup: 0 
        fsGroup: 0
      serviceAccountName: {{ include "pgadmin.serviceAccountName" . }}
      containers:
      - name: pgadmin4
        image: {{ .Values.imageName }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /misc/ping
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 5
        command:
          {{- toYaml .Values.command | nindent 12 }}
        args:
          {{- toYaml .Values.args | nindent 12 }}
        env:
          - name: PGADMIN_PORT
            value: "{{ .Values.port }}"
