---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector: 
    {{- include "pgadmin.selectorLabels" . | nindent 4 }}
