#  Copyright 2023-2024 Dataport AöR
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

{{- if .Values.applications }}
{{- range $app := .Values.applications }}
{{- $source := required "Please specify a source under .Values.source" $.Values.source }}
{{- $sourceRef := "main" }}
{{- if hasKey $app "sourceRef" }}
{{- $sourceRef = $app.sourceRef }}
{{- else if hasKey $.Values "sourceRef" }}
{{- $sourceRef = $.Values.sourceRef }}
{{- end }}
{{- $project := "default" }}
{{- if hasKey $app "project" }}
{{- $project = $app.project }}
{{- else if hasKey $.Values "project" }}
{{- $project = $.Values.project }}
{{- end }}
{{- $namespace := "default" }}
{{- if hasKey $app "namespace" }}
{{- $namespace = $app.namespace }}
{{- else if hasKey $.Values "namespace" }}
{{- $namespace = $.Values.namespace }}
{{- end }}
{{- if $app.source }}
{{- $source = $app.source }}
{{- end }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{ if hasKey $app "namespace" }}
  name: {{ .name }}-{{ $project }}
  {{- else }}
  name: {{ .name }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- if .values }}
{{- if .values.fullnameOverride }}
{{- if contains .values.fullnameOverride .name }}
    app.kubernetes.io/instance: {{ .values.fullnameOverride }}
{{- end }}
{{- else }}
    app.kubernetes.io/instance: {{ .name }}
{{- end }}
{{- end }}
{{- if .cascadeDeletion }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
{{- end }}
spec:
  destination:
    namespace: {{ $namespace }}
    {{- if .serverName }}
    name: {{ .serverName }}
    {{- else }}
    server: {{ .k8sAPI | default "https://kubernetes.default.svc" }}
    {{- end }}
  project: {{ $project }}
{{- if not .sources }}
  source:
{{- if or .helmValues .values }}
    helm:
      releaseName: {{ .name }}
{{- if .skipCrds }}
      skipCrds: true
{{- end }}
{{- if .helmValues }}
      valueFiles:
{{- toYaml .helmValues | nindent 8 }}
{{- end }}
{{- if .values }}
      values: |
{{- toYaml .values | nindent 8 }}
{{- end }}
{{- end }}
    {{- if .sourcePath }}
    path: {{ .sourcePath | default "." }}
    {{- end }}
    repoURL: {{ $source }}
    targetRevision: {{ $sourceRef | quote }}
    {{- if not .sourcePath }}
    chart: {{ .chartName | default .name }}
    {{- end }}
    {{- if .directory }}
    directory:
      {{- if .directory.recurse }}
      recurse: true
      {{- end }}
      {{- if .directory.include }}
      include: {{ .directory.include | quote }}
      {{- end }}
      {{- if .directory.exclude }}
      exclude: {{ .directory.exclude | quote }}
      {{- end }}
    {{- end }}
{{- end }}
  {{- if hasKey $app "sources" }}
  sources:
  {{- range $sources := .sources }}
    {{- if .repoURL }}
  - repoURL: {{ .repoURL }}
    {{- else }}
  - repoURL: {{ $source }}
    {{- end }}
    {{- if .ref }}
    ref: {{ .ref }}
    {{- end }}
{{- if or .helmValues .values }}
    helm:
      releaseName: {{ .name }}
{{- if .skipCrds }}
      skipCrds: true
{{- end }}
{{- if .helmValues }}
      valueFiles:
{{- toYaml .helmValues | nindent 8 }}
{{- end }}
{{- if .values }}
      values: |
{{- toYaml .values | nindent 8 }}
{{- end }}
{{- end }}
    {{- if .sourcePath }}
    path: {{ .sourcePath | default "." }}
    {{- end }}
    {{- if .sourceRef }}
    targetRevision: {{ .sourceRef | quote }}
    {{- else }}
    targetRevision: {{ $sourceRef | quote }}
    {{- end }}
    {{- if and (not .sourcePath) (not .ref) }}
    chart: {{ .chartName | default $app.name }}
    {{- else if .chartName }}
    chart: {{ .chartName }}
    {{- end }}
    {{- if .directory }}
    directory:
      {{- if .directory.recurse }}
      recurse: true
      {{- end }}
      {{- if .directory.include }}
      include: {{ .directory.include | quote }}
      {{- end }}
      {{- if .directory.exclude }}
      exclude: {{ .directory.exclude | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  syncPolicy:
    automated:
      {{- if or .syncPolicyPrune (not (hasKey . "syncPolicyPrune")) }}
      prune: true
      {{- end }}
      {{- if or .syncPolicyselfHeal (not (hasKey . "syncPolicyselfHeal")) }}
      selfHeal: true
      {{- end }}
      {{- if or .syncPolicyselfAllowEmpty (not (hasKey . "syncPolicyselfAllowEmpty")) }}
      allowEmpty: true
      {{- end }}
    syncOptions:
      - Validate=true
    {{- if or .createNamespace (not (hasKey . "createNamespace")) }}
      - CreateNamespace=true
    {{- end }}
    {{- if .extraSyncOptions }}
    {{- toYaml .extraSyncOptions | nindent 6}}
    {{- end }}
  ignoreDifferences:
    {{- if .ignoreDifferences }}
    {{- toYaml .ignoreDifferences | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
