source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: dev

applications:
  - name: marketplace
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/marketplace.yaml"
        sourcePath: charts/marketplace
        name: marketplace
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: keycloak
    namespace: keycloak
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: keycloak
      - repoURL: https://codecentric.github.io/helm-charts
        sourceRef: ~18.4.3
        chartName: keycloak
        helmValues:
          - "$keycloak/environments/dev/keycloak.yaml"

  - name: rabbitmq
    namespace: rabbitmq
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: rabbitmq
      - repoURL: https://charts.bitnami.com/bitnami
        sourceRef: 11.16.2
        chartName: rabbitmq
        helmValues:
          - "$rabbitmq/environments/demo/rabbitmq.yaml"

  - name: gxfs-catalog
    namespace: gxfs
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/gxfs-catalog
    helmValues:
      - "../../environments/dev/gxfs-catalog.yaml"

  - name: shared-resources
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/dev/shared-resources.yaml"

  - name: aaam-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/aaam-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: aaam-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: organisations-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/organisations-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: organisations-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: creation-wizard-api
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/creation-wizard-api.yaml"
        sourcePath: charts/orchestrator
        name: creation-wizard-api
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: serviceoffering-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/serviceoffering-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: serviceoffering-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: contract-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/contract-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: contract-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: edc-1
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-1.yaml"

  - name: edc-2
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-2.yaml"

  - name: edc-imc
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-imc.yaml"

  - name: edc-chempoint
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-chempoint.yaml"

  - name: edc-headai
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-headai.yaml"

  - name: edc-lightcast
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-lightcast.yaml"

  - name: ssi-aas-auth-service
    namespace: ssi-aas
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-auth-service
        helmValues:
          - "$values/environments/dev/ssi/aas-auth-service.yaml"
        repoURL: 'https://gitlab.eclipse.org/eclipse/xfsc/authenticationauthorization.git'
        sourcePath: deploy/helm/Integration
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-cache
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-tsa-cache
        helmValues:
          - "$values/environments/dev/ssi/tsa-cache.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/cache.git'
        sourcePath: deployment/helm
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-infohub
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-tsa-infohub
        helmValues:
          - "$values/environments/dev/ssi/tsa-infohub.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/infohub.git'
        sourcePath: deployment/helm
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-policy
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-tsa-policy
        helmValues:
          - "$values/environments/dev/ssi/tsa-policy.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/policy.git'
        sourcePath: deployment/helm
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-signer
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-tsa-policy
        helmValues:
          - "$values/environments/dev/ssi/tsa-signer.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/signer.git'
        sourcePath: deployment/helm
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-task
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-tsa-task
        helmValues:
          - "$values/environments/dev/ssi/tsa-task.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/task.git'
        sourcePath: deployment/helm
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values

  - name: ssi-tsa-redis
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: redis
      - repoURL: https://marketplace.azurecr.io/helm/v1/repo
        sourceRef: ~17.3.11
        chartName: redis

  - name: ssi-tsa-nats
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: nats
      - repoURL: https://nats-io.github.io/k8s/helm/charts/
        sourceRef: ~1.1.5
        chartName: nats
        helmValues:
          - $nats/environments/dev/ssi/tsa-nats.yaml

  - name: ssi-tsa-vault
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: vault
      - repoURL: https://helm.releases.hashicorp.com
        sourceRef: ~0.26.1
        chartName: vault
        helmValues:
          - $vault/environments/dev/ssi/tsa-vault.yaml

  - name: ssi-tsa-mongodb
    namespace: ssi-tsa
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: mongodb
      - repoURL: https://marketplace.azurecr.io/helm/v1/repo
        sourceRef: ~13.3.1
        chartName: mongodb
        helmValues:
          - $mongodb/environments/dev/ssi/tsa-mongodb.yaml