source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: dev

applications:
  - name: marketplace
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/marketplace.yaml"
        sourcePath: charts/marketplace
        name: marketplace
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: keycloak
    namespace: keycloak
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: keycloak
      - repoURL: https://codecentric.github.io/helm-charts
        sourceRef: ~18.4.3
        chartName: keycloak
        helmValues:
          - "$keycloak/environments/dev/keycloak.yaml"

  - name: rabbitmq
    namespace: rabbitmq
    enabled: true
    serverName: dev-cluster
    sources:
      - ref: rabbitmq
      - repoURL: https://charts.bitnami.com/bitnami
        sourceRef: 11.16.2
        chartName: rabbitmq
        helmValues:
          - "$rabbitmq/environments/demo/rabbitmq.yaml"

  - name: gxfs-catalog
    namespace: gxfs
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/gxfs-catalog
    helmValues:
      - "../../environments/dev/gxfs-catalog.yaml"

  - name: shared-resources
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/dev/shared-resources.yaml"

  - name: aaam-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/aaam-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: aaam-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: organisations-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/organisations-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: organisations-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: creation-wizard-api
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/creation-wizard-api.yaml"
        sourcePath: charts/orchestrator
        name: creation-wizard-api
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: serviceoffering-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/serviceoffering-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: serviceoffering-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: contract-orchestrator
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sources:
      - helmValues:
          - "../../environments/dev/contract-orchestrator.yaml"
        sourcePath: charts/orchestrator
        name: contract-orchestrator
      - sourcePath: "app-decorators/dispatch-cypress"

  - name: edc-1
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-1.yaml"

  - name: edc-2
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-2.yaml"

  - name: edc-imc
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-imc.yaml"

  - name: edc-chempoint
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-chempoint.yaml"

  - name: edc-headai
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-headai.yaml"

  - name: edc-lightcast
    namespace: merlot
    enabled: true
    serverName: dev-cluster
    sourcePath: charts/merlot-edc
    helmValues:
      - "../../environments/dev/edc-lightcast.yaml"

  - name: ssi-auth-service
    namespace: ssi-aas
    enabled: true
    serverName: dev-cluster
    sources:
      - name: ssi-auth-service
        helmValues:
          - "$values/environments/dev/ssi/aas-auth-service.yaml"
        repoURL: 'https://gitlab.eclipse.org/mjuergenscg/authenticationauthorization.git'
        sourcePath: deploy/helm/Integration
        sourceRef: feature/generalized-helm-chart
      - repoURL: 'https://github.com/merlot-education/gitops.git'
        targetRevision: main
        ref: values