source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: dev

applications:
  - name: marketplace-dev
    namespace: dev
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/dev/marketplace.yaml"

  - name: aaam-orchestrator-dev
    namespace: dev
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/dev/aaam-orchestrator.yaml"
