source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: dev

applications:
  - name: dev-marketplace
    namespace: dev
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/dev/marketplace.yaml"

  - name: dev-keycloak
    namespace: dev
    enabled: true
    sources:
      - ref: keycloak
      - repoURL: https://codecentric.github.io/helm-charts
        sourceRef: 18.4.0
        chartName: keycloak
        helmValues:
          - "$keycloak/environments/dev/keycloak.yaml"

  - name: dev-rabbitmq
    namespace: dev
    enabled: true
    sources:
      - ref: rabbitmq
      - repoURL: https://charts.bitnami.com/bitnami
        sourceRef: 11.16.2
        chartName: rabbitmq
        helmValues:
          - "$rabbitmq/environments/dev/rabbitmq.yaml"

  - name: dev-gxfs-catalog
    namespace: dev
    enabled: true
    sourcePath: charts/gxfs-catalog
    helmValues:
      - "../../environments/dev/gxfs-catalog.yaml"

  - name: dev-shared-resources
    namespace: dev
    enabled: true
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/dev/shared-resources.yaml"

  - name: dev-aaam-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/aaam-orchestrator.yaml"

  - name: dev-organisations-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/organisations-orchestrator.yaml"

  - name: dev-creation-wizard-api
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/creation-wizard-api.yaml"

  - name: dev-serviceoffering-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/serviceoffering-orchestrator.yaml"

  - name: dev-contract-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/contract-orchestrator.yaml"