source: https://github.com/merlot-education/gitops.git
sourceRef: main
namespace: argocd
project: dev

applications:
  - name: dev-marketplace
    namespace: dev
    enabled: true
    sourcePath: charts/marketplace
    helmValues:
      - "../../environments/dev/marketplace.yaml"

  - name: dev-shared-resources
    namespace: dev
    enabled: true
    sourcePath: charts/shared-resources
    helmValues:
      - "../../environments/dev/shared-resources.yaml"

  - name: dev-aaam-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/aaam-orchestrator.yaml"

  - name: dev-organisations-orchestrator
    namespace: dev
    enabled: true
    sourcePath: charts/orchestrator
    helmValues:
      - "../../environments/dev/organisations-orchestrator.yaml"
